### ISSUE TITLE
Potentially invalid `--format` option in docopt string

### ISSUE THREAD

**Issue by felixSchl** [toenu23/nxtpm#1]
Hey, I am the author of neodoc, I am happy to see this project using it :)
I just noticed one little thing in your docopt string: `[--format=tgz|zip]`, which
neodoc will understand as `[--format=tgz | zip]`, so either a `--format=tgz` option
OR a `zip` positional. You can avoid this ambiguity by enclosing the string `[--format=<tgz|zip>]`.

**Comment by toenu23** [comment]
Corrected it.
--format option is not implemented yet, so I didn't catch this.
Thanks for the heads up, and for neodoc :)
